### ISSUE TITLE
I don't have a settings button. Does anybody else have that issue?

### ISSUE THREAD

**Issue by seeker191** [githubteacher/intro-december-2015#29]

**Comment by rizan-v2** [comment]
@seeker191 This is only for the person/company who owns the repo.

**Comment by githubteacher** [comment]
For repositories owned by an individual (like this one, owned by @githubteacher), only the repository owner has the settings icon. Repositories can also be owned by organizations (a team or company) -- in an organization-owned repository, the organization can grant individuals or teams access to admin settings for the repository.
