### ISSUE TITLE
Hello from Lehigh University! 

### ISSUE THREAD

**Issue by deyshin** [githubteacher/intro-december-2015#41]
## GO LEHIGH

_look forward to be back in coding!_

**Comment by laurauzcategui** [comment]
#42 :) Christmas message

**Comment by RussellJQA** [comment]
Are you at Lehigh now?

I graduated from Lehigh in 1985.

**Comment by ogalchonok** [comment]
Hello there! Are you teaching at the University or studying?

**Comment by deyshin** [comment]
@RussellJohnson Hi! I'm at Lehigh now, finishing up my M.S. in Computer Engineering! I did my undergrad here too. Class of 2014! Nice to meet you :) 
PS. We crushed Lafayette this yer :+1:

**Comment by deyshin** [comment]
@ogalchonok 
I'm studying at Lehigh right now! I've tutored for quite a few years now, if that counts :smile:

**Comment by deyshin** [comment]
@laurauzcategui 
It's beginning to look a lot like Christmas! :musical_note:

**Comment by ogalchonok** [comment]
Oh, how cool! It is gonna be exiting when you are finished with your studies :+1:  Sure, tutoring counts  a lot ! :-D :-D I have some teaching experience and now I am studying frontend development. That is why I really need Git.
Nice to meet you too. Sure, it is like Christmas now. It was even snowing once here in Denmark :-D
Cool, so you are a "crusher"? he he ;-)
