### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jfcandidofilho** [githubteacher/intro-december-2015#92]
Can't create branches; dunno why :dancers:

**Comment by githubteacher** [comment]
@jfcandidofilho Looks like you are not a repository collaborator. Did you comment on #3 ?

**Comment by jfcandidofilho** [comment]
No; I probably lost something as I arrived 30 minutes late - I had a surgery just a little ago.

I will try it.

**Comment by jfcandidofilho** [comment]
It works; already did what was meant to do! Thanks, master yoda! :+1:
